name: build
on: [push, pull_request]
jobs:
  binaries:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: 'x64'
          - os: windows-latest
            arch: 'x64'
          - os: windows-latest
            arch: 'x86'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: ${{ matrix.arch }}
      - name: Double-check Python version
        run: |
          python --version
      - name: Clone Git repository (with submodules)
        uses: actions/checkout@v2
        with:
          path: git-repo
          submodules: true
      - name: Install Python package
        working-directory: git-repo
        run: |
          python -m pip install .
      - name: Run tests
        working-directory: git-repo
        run: |
          chmod +x make_dist.sh
          ./make_dist.sh
          cd build
          ls
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{env._GITHUB_PAT}}
        uses: softprops/action-gh-release@v1
        with:
          files: build/*  # Specify the path to your build artifacts
          tag_name: ${{ github.ref }}
          title: Release ${{ github.ref }}
